backend:
  name: git-gateway
  repo: amademort/www
  branch: master
  
media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: PGS
    folder: content/pages
    create: true
    fields:
      - { name: title, label: title }
      - { name: description, label: description }
      - { name: date, label: date, widget: date }

      - { name: thumbnail, label: thumbnail, widget: image }

      - { name: draft, label: draft, widget: boolean, default: false }

      - { name: body, label: body, widget: markdown }

  - name: img
    label: IMG
    folder: content/gallery/img
    create: true
    fields:
      - { name: title, label: title }
      - { name: description, label: description }
      - { name: date, label: date, widget: date }

      - { name: thumbnail, label: thumbnail, widget: image }

       - { name: categories, label: categories, widget: select, multiple: true, options: [code, photo, audio, video, design], default: [photo]}
      - { name: tags, label: tags, widget: list, field: { name: tag, label: tag } }
      - { name: tools, label: tools, widget: list, field: { name: tool, label: tool }, default: [É‘6400] }

      - { name: draft, label: draft, widget: boolean, default: false }
      - { name: featured, label: featured, widget: boolean, default: false }

      - { name: body, label: body, widget: markdown }
