backend:
  name: git-gateway
  repo: amademort/www
  branch: master
  
media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: language, label: Language, widget: select, options: [de, en], default: [de]}
      - { name: body, label: Body, widget: markdown }

  - name: photos
    label: Photos
    folder: content/projects/photo
    create: true
    fields:
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: featured, label: Featured, widget: boolean, default: false }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list, field: { name: tag, label: Tag } }
      - { name: category, label: Category, widget: select, multiple: true, options: [code, photo, audio, video, design], default: [photo]}
      - { name: tools, label: Tools, widget: list, field: { name: tool, label: Tool }, default: [É‘6400] }
      - { name: body, label: Body, widget: markdown }
